//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        public int ID_Competition { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Prize { get; set; }
        public double MinValue { get; set; }
        public System.DateTime ApplicationDeadline { get; set; }
    }
}
