//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KonkursProektovEntities : DbContext
    {
        public KonkursProektovEntities()
            : base("name=KonkursProektovEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Competition> Competition { get; set; }
        public virtual DbSet<Evalulation> Evalulation { get; set; }
        public virtual DbSet<Experts> Experts { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Users_Request> Users_Request { get; set; }
    }
}
