//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evalulation
    {
        public int Request_ID { get; set; }
        public int Expert_ID { get; set; }
        public string Name { get; set; }
        public double EvalulationNum { get; set; }
    }
}
